sudo: false

language: go

go:
 - 1.3.3
 - 1.4.2
 - tip

env:
  global:
   - secure: "GYPf9iqbY/5YLmorhVxH2Q4Y8/kxF3MWxDau8Sb2QnineLAJZA2HKi4aWdZIoK8AMAJgXdHUC4Pw2jywp9nC2Q+TW1+57tp0uLLIdghuwif78oyqykhlt11ny+SUk5PAkqYmm+dCbA0kxShg1hFFfHGTTiDuWklTWomxGGICSPc="

before_install:
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
 - go get github.com/mattn/goveralls

script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .test-coverage.sh; fi

after_failure: failure

notifications:
  email:
    recipients:
      - jonathan.lawlor@gmail.com
    on_success: change
    on_failure: always
